### ISSUE TITLE
How to delete a module on dashboard?

### ISSUE THREAD

**Issue by riezebosch** [stryker-mutator/stryker-dashboard#173]
I want to rename the module but can't seem to replace or remove the old one: https://dashboard.stryker-mutator.io/reports/github.com/riezebosch/CommandLiners/master

**Comment by lbragile** [comment]
Is there a solution to this?

I recently parallelized my mutation tests and updated the modules, now the old modules are still present and impact the overall score even though they are not actually tested anymore.

Any help/suggestion would be appreciated.

**Comment by lbragile** [comment]
@hugo-vrijswijk @riezebosch I think I found a solution.

You can create an empty file at the root of your directory which you can ignore in .gitignore, let's call it **temp_mutation.js**
Then you simply run a command with and set your API key as environment variable making sure to specify the module to be same as your old ones.

Assume I have an old module named **App**
To remove it I would run the following command (on Windows):

`set STRYKER_DASHBOARD_API_KEY=YOUR_API_KEY&& npx stryker run -m temp_mutation.js App`

Notice that there is no space between `YOUR_API_KEY` and `&&` - on purpose. Otherwise you will set `STRYKER_DASHBOARD_API_KEY` to `YOUR_API_KEY ` - notice the extra space, and it won't work properly.

Since the mutated file is empty, there are no mutants and thus the module is removed!

Hope this helps.

**Comment by xandervedder** [comment]
This is currently not possible, but I do plan on implementing this eventually.

I will track this in #246 though, since I think the same is being asked (correct me if I am wrong).
