### ISSUE TITLE
Stryker dashboard support for private repos

### ISSUE THREAD

**Issue by davidsteelebrady** [stryker-mutator/stryker-dashboard#186]
**Question**

Does https://dashboard.stryker-mutator.io/ support private org repos? I can see my public repos but no way to authorise access to my private repos held under my enterprise? 

**Stryker environment**

```
+-- @stryker-mutator/core@x.x.x
+-- @stryker-mutator/xxx-xxx@x.x.x
```

```
+-- mocha@x.x.x
+-- jest@x.x.x
+-- karma@x.x.x
+-- angular-cli@x.x.x
+-- react-scripts@x.x.x
```

**Additional context**

N/A

**Comment by nicojs** [comment]
Thanks for your issue. We currently don't support private repo's. The reason for that is that Stryker will by default also send the source code to the dashboard and since reports are publicly available... bye-bye private code 🤷‍♂️

We will have to do some work to get this supported. It is planned but would take at least a year to implement with the current rate of features.

**Comment by davidsteelebrady** [comment]
thanks @nicojs will keep an eye out for updates.
