### ISSUE TITLE
Hot Reloading Stryker elements

### ISSUE THREAD

**Issue by lex-funy** [stryker-mutator/stryker-dashboard#543]
To make development of the frontend easier, it would be nice to have the frontend reload when changes are made to Stryker elements.

In the current state of the project Stryker elements needs to manually be rebuild.

**Comment by xandervedder** [comment]
It should be doable with something like: https://vitejs.dev/guide/build.html#rebuild-on-files-changes and then maybe specifying angular to watch for changes made in a different directory (not sure how yet).

**Comment by xandervedder** [comment]
I was also busy with trying to make hot reloading work from the backend -> frontend using a reverse proxy. It doesn't really work that well since we should proxy everything including websockets but that is where things didn't work yet.

Definitely should use something like `http-proxy` or the express middleware.

**Comment by xandervedder** [comment]
This already works now. Run stryker-elements in watch mode and the frontend will reload when something in stryker-elements changes.
